#pragma once

#define NONE_FORMAT                 "\x1b[0m"
#define BOLD                        "\x1b[1m"
#define BLACK                       "\x1b[30m"
#define RED                         "\x1b[31m"
#define GREEN                       "\x1b[32m"
#define YELLOW                      "\x1b[33m"
#define BLUE                        "\x1b[34m"
#define PURPLE                      "\x1b[35m"
#define CYAN                        "\x1b[36m"
#define WHITE                       "\x1b[37m" 
#define BLACK_BOLD                  "\x1b[1;30m"
#define RED_BOLD                    "\x1b[1;31m"
#define GREEN_BOLD                  "\x1b[1;32m"
#define YELLOW_BOLD                 "\x1b[1;33m"
#define BLUE_BOLD                   "\x1b[1;34m"
#define PURPLE_BOLD                 "\x1b[1;35m"
#define CYAN_BOLD                   "\x1b[1;36m"
#define WHITE_BOLD                  "\x1b[1;37m" 
#define BLACK_BACKGROUND            "\x1b[41m"                  
#define RED_BACKGROUND              "\x1b[41m"
#define GREEN_BACKGROUND            "\x1b[42m"    
#define YELLOW_BACKGROUND           "\x1b[43m"
#define BLUE_BACKGROUND             "\x1b[44m"
#define PURPLE_BACKGROUND           "\x1b[45m"
#define CYAN_BACKGROUND             "\x1b[46m"
#define WHITE_BACKGROUND            "\x1b[47m"
